# Generated by Django 5.2.2 on 2025-08-24 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_slug_alter_post_image_alter_post_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('published', 'Опубликован'), ('draft', 'Черновик')], default='draft', verbose_name='Статус'),
        ),
    ]
